export const HOME_CATEGORIES_BEGIN = 'HOME_CATEGORIES_BEGIN';
export const HOME_CATEGORIES_SUCCESS = 'HOME_CATEGORIES_SUCCESS';
export const HOME_CATEGORIES_FAILURE = 'HOME_CATEGORIES_FAILURE';
export const HOME_CATEGORIES_DISMISS_ERROR = 'HOME_CATEGORIES_DISMISS_ERROR';
export const HOME_CATEGORY_BEGIN = 'HOME_CATEGORY_BEGIN';
export const HOME_CATEGORY_SUCCESS = 'HOME_CATEGORY_SUCCESS';
export const HOME_CATEGORY_FAILURE = 'HOME_CATEGORY_FAILURE';
export const HOME_CATEGORY_DISMISS_ERROR = 'HOME_CATEGORY_DISMISS_ERROR';
